apiVersion: v1
kind: Pod
metadata:
  name: bmo-cloud-scheduler
  labels:
    name: bmo-cloud-scheduler
spec:
  containers:
    - name: bmo-cloud-scheduler
      image: localhost:32000/bmo-cloud-scheduler
      env:
        - name: NOTION_KEY
          valueFrom:
            secretKeyRef:
              name: bmo-cloud-scheduler-secrets
              key: NOTION_KEY
              optional: false
        - name: NOTES_DBID
          valueFrom:
            secretKeyRef:
              name: bmo-cloud-scheduler-secrets
              key: NOTES_DBID
              optional: false
        - name: TASKS_DBID
          valueFrom:
            secretKeyRef:
              name: bmo-cloud-scheduler-secrets
              key: TASKS_DBID
              optional: false
