on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - name: Execute
      uses: fjogeleit/http-request-action@v1
      with:
        url: '${{ secrets.NETLIFY_URL }}/.netlify/functions/add-daily-note-section'
        method: 'GET'